# Generated by Django 5.1 on 2024-09-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='parse_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
