# Generated by Django 5.1 on 2024-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_hub_parse_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauthor',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
